name: docs
on:
  push:
    branches:
      - master
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install --user --no-cache-dir Cython
          pip install --user -r requirements.txt
      - name: Discover typos with codespell
        run: |
          pip install codespell
          codespell --skip=".*,.git/*,*.csv,*.geojson,*.json,*.js,*.html,*cff,*.pdf" --ignore-words-list="aci,acount,acounts,fallow,hart,hist,nd,ned,ois,wqs"
      - name: Install dependencies
        run: pip install mkdocs-material mkdocstrings mkdocs-git-revision-date-plugin mkdocs-jupyter mkdocs-pdf-export-plugin ipykernel
      - name: depoly
        run: mkdocs gh-deploy --force
        env:
          RUN_GITHUB_ACTION: ${{ secrets.RUN_GITHUB_ACTION }}
